// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocwnidfmvrwarhspdrou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jd25pZGZtdnJ3YXJoc3Bkcm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODA2NzUsImV4cCI6MjA1ODk1NjY3NX0.Btoi6tooGziaXbtxixZwCiYZ8H45Afiobwqm6PFQ1W4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);