
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocwnidfmvrwarhspdrou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jd25pZGZtdnJ3YXJoc3Bkcm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODA2NzUsImV4cCI6MjA1ODk1NjY3NX0.Btoi6tooGziaXbtxixZwCiYZ8H45Afiobwqm6PFQ1W4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Pour déboguer les requêtes Supabase
const debugSupabase = false; // Mettre à true pour activer les logs
if (debugSupabase) {
  // Using console.log for debugging instead of event listeners
  console.log('Supabase client initialized with URL:', SUPABASE_URL);
  
  // We can attach event listeners in a different way or use try/catch for error handling
  const originalRequest = supabase.auth.getSession;
  supabase.auth.getSession = async () => {
    try {
      const result = await originalRequest.call(supabase.auth);
      return result;
    } catch (error) {
      console.error('Supabase auth error:', error);
      throw error;
    }
  };
}
